# Generated by Django 3.2.9 on 2023-06-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('estado', models.CharField(choices=[('entrada', 'entrada'), ('salida', 'salida')], default='salida', max_length=8)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persona',
                'ordering': ['id'],
            },
        ),
    ]
