# Generated by Django 3.2.9 on 2023-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0002_auto_20230623_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='estado',
            field=models.CharField(default='Salida', max_length=8),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado',
            field=models.CharField(choices=[('entrada', 'entrada'), ('salida', 'salida')], default='Salida', max_length=8),
        ),
    ]
