# Generated by Django 3.2.9 on 2023-07-01 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0003_auto_20230623_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personamodel',
            name='qr',
        ),
    ]
