# Generated by Django 3.2.9 on 2023-07-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0004_remove_personamodel_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='cedula',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='personamodel',
            name='placa',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Salida'),
        ),
        migrations.AddField(
            model_name='personamodel',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Vehiculo'),
        ),
    ]
