# Generated by Django 3.2.9 on 2023-07-22 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0006_registro_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='personamodel',
            name='tipousuario',
            field=models.CharField(default='Unemi', max_length=8),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado',
            field=models.CharField(default='Salida', max_length=8),
        ),
        migrations.AlterField(
            model_name='registro',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
