# Generated by Django 3.2.9 on 2023-08-05 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0007_auto_20230722_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPersonaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descipcion', models.CharField(default='Descripcion', max_length=250)),
                ('estado', models.CharField(default='Estado', max_length=12)),
            ],
            options={
                'verbose_name': 'TipoPersona',
                'verbose_name_plural': 'TipoPersonas',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='estado',
            field=models.CharField(blank=True, default='Salida', max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='VehiculoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='Color', max_length=8, null=True)),
                ('modelo', models.CharField(blank=True, default='Modelo', max_length=20, null=True)),
                ('placa', models.CharField(blank=True, default='Placa', max_length=8, null=True)),
                ('estado', models.CharField(blank=True, default='Estado', max_length=8, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='tipousuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TipoUsuario', to='PrincipalApp.tipopersonamodel'),
        ),
    ]
