# Generated by Django 3.2.9 on 2023-08-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0009_auto_20230805_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personamodel',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='personamodel',
            name='vehiculo',
        ),
    ]
