# Generated by Django 3.2.9 on 2023-08-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0010_auto_20230805_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, default='Observacion', max_length=250, null=True)),
                ('estado', models.CharField(blank=True, default='Estado', max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='registro',
            name='novedades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Novedades', to='PrincipalApp.novedadesmodel'),
        ),
    ]
