# Generated by Django 3.2.9 on 2023-08-10 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0017_rename_descipcion_tipopersonamodel_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='fecha_creacion',
            new_name='fecha_entrada',
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
