# Generated by Django 3.2.9 on 2023-08-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrincipalApp', '0018_auto_20230810_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
